@startuml naam
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(lid, "Lid")
Person(medewerker, "Medewerker")
Person(beheerder, "Beheerder")
Person(wedstrijdCom, "Wedstrijdcommisaris")
Person(matCom, "Materiaalcommisaris")

LAYOUT_LEFT_RIGHT

System_Boundary(reserveerSysteem, "Reserveer Systeem"){
    Container(app, "Roei-Je-Rot Desktop App", "C#, .Net Core, WPF, Entity Framework")
    Container(api, "Roei-Je-Rot API", "C#, .NET Core, Entity Framework, ASP.NET")
    Container(webapp, "Roei-Je-Rot Web App", "C#, .NET Core, Entity Framework, ASP.NET")
    
    ContainerDb(db, "Roei-Je-Rot Database", "MS-SQL")

    Rel(app, db, "Stuurt aan")
    Rel(api, db, "Stuurt aan")
    Rel(webapp, api, "Doet aanvragen aan", "JSON, HTTPS")
}

System_Ext(mail, "Gmail API")
Rel(app, mail, "Vraagt om bericht te sturen")
Rel(webapp, mail, "Vraagt om bericht te sturen")
Rel(mail, lid, "Stuur mails naar")


Rel(lid, app, "Maakt reserveringen met")
Rel(lid, webapp, "Maakt reserveringen met", "HTTPS")
Rel(medewerker, app, "Boten innemen en uitnemen en schade melden")
Rel(beheerder, app, "Nieuwe boten en leden aanmaken en beheren")
Rel(wedstrijdCom, app, "Wedstrijden organiseren en beheren")
Rel(matCom, app, "Handelt schade af")

@enduml